%% DIPLOMOVÁ PRÁCE
%  BIOMETRICKÉ ROZPOZNÁNÍ ŽIVOSTI PRSTU
%  BC. TOMÁŠ VÁÒA, 2015
%  GUI - GRAFICKÉ UŽIVATELSKÉ ROZHRANÍ

function program()

    close all;

    % Zjištìní velikosti obrazovky, aby GUI bylo na vsech monitorech stejné
    velikost_obrazovky = get(0, 'ScreenSize');
    
    % Nastaveni samotného GUI (název, velikost okna)
    figure('NumberTitle', 'off',...
           'MenuBar', 'none',...
           'Name', 'Biometrické rozpoznání živosti prstu',...
           'Resize', 'off',...
           'Position', [(1 / 6) * velikost_obrazovky(3), (1 / 10) * velikost_obrazovky(4), (2 / 7) * velikost_obrazovky(3), (45 / 120) * velikost_obrazovky(3)]);
    
    % Nastavení barvy os pro zobrazení otisku  
    axes('Units', 'pixels',...
         'XTickLabel', '',...
         'YTickLabel', '',...
         'XColor', 'w',...
         'YColor', 'w',...
         'Position', [(1 / 60) * velikost_obrazovky(3), (8 / 100) * velikost_obrazovky(3), (53 / 210) * velikost_obrazovky(3), (1 / 4) * velikost_obrazovky(3)]);
    
    % Tlaèítko pro naètení otisku 
    uicontrol('Style', 'pushbutton',...
              'Units', 'pixels',...
              'String', 'Naèíst otisk',...
              'Position', [(1 / 60) * velikost_obrazovky(3), (34 / 100) * velikost_obrazovky(3), (1 / 15) * velikost_obrazovky(3), (1 / 50) * velikost_obrazovky(3)],...
              'Callback', @algoritmus); % zavolani funkce, vypocet priznaku
    
    % Pole pro výpis cesty k souboru s otiskem prstu      
    uicontrol('Style', 'edit',...
              'HorizontalAlignment', 'left',...
              'Enable', 'off',...
              'Position', [(1 / 11) * velikost_obrazovky(3), (1091 / 3200) * velikost_obrazovky(3), (71 / 400) * velikost_obrazovky(3), (1 / 55) * velikost_obrazovky(3)],...
              'Tag', 'cesta_edit');
    
    % Pole pro výsledek detekce živosti      
    uicontrol('Style', 'text',...
              'Tag', 'hodnoceni_text',...
              'Units', 'pixels',...
              'FontSize', 40,...
              'String', '',...
              'Visible', 'off',...
              'Position', [(1 / 60) * velikost_obrazovky(3), (3 / 200) * velikost_obrazovky(3), (53 / 210) * velikost_obrazovky(3), (5 / 90) * velikost_obrazovky(3)]);
end